# ===================================================
# Backtest Configuration File
# This file defines the parameters for manual backtesting.
# Edit this file to change symbol, timeframe, and date range.
# ===================================================

backtest:
  # نماد معاملاتی (مطابق API صرافی CoinEx)
  symbol: "BTC-USDT"

  # تایم‌فریم کندل‌ها
  # مقادیر مجاز: 1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 12h, 1d, 3d, 1w
  timeframe: "1h"

  # بازه زمانی بکتست (فرمت ISO 8601)
  start_date: "2023-01-01T00:00:00"
  end_date: "2024-01-01T00:00:00"

  # تعداد کندل‌ها (اختیاری - اگر تاریخ تعیین شود، این مورد نادیده گرفته می‌شود)
  limit: 1000

  # حالت بکتست
  # manual: با استفاده از تاریخ یا limit
  # live_preview: فقط برای آینده (در حالت لایو)
  mode: "manual"

# ===================================================
# Risk & Trade Management (اختیاری - می‌توان در settings.json هم باشد)
# ===================================================
risk:
  stop_loss_percent: 1.0
  take_profit_percent: 3.0
  position_size_usdt: 100

# ===================================================
# Debug & Logging
# ===================================================
debug:
  enable_logging: true
  log_level: "INFO"
  save_raw_data: true
