name: 🚀 Run Mutanabby Backtest

on:
  workflow_dispatch:
    inputs:
      symbol:
        type: string
        description: 'نماد مورد نظر (مثلاً BTC-USDT)'
        required: true
        default: 'BTC-USDT'
      timeframe:
        type: string
        description: 'تایم‌فریم (مثلاً 1h, 4h, 15m)'
        required: true
        default: '1h'
      start_date:
        type: string
        description: 'تاریخ شروع (فرمت: YYYY-MM-DD)'
        required: true
        default: '2024-01-01'
      end_date:
        type: string
        description: 'تاریخ پایان (فرمت: YYYY-MM-DD)'
        required: true
        default: '2024-06-01'

jobs:
  backtest:
    runs-on: ubuntu-latest

    steps:
      - name: 🔎 Checkout Code
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Install Dependencies
        run: |
          pip install --upgrade pip
          pip install ccxt pandas numpy python-telegram-bot

      - name: 🛠️ Generate config.py from Inputs
        env:
          SYMBOL: ${{ replace(github.event.inputs.symbol, '-', '/') }}
          TIMEFRAME: ${{ github.event.inputs.timeframe }}
          START_DATE: ${{ github.event.inputs.start_date }}
          END_DATE: ${{ github.event.inputs.end_date }}
        run: |
          cat > config.py <<EOL
# Auto-generated by GitHub Actions
SYMBOL = "$SYMBOL"
TIMEFRAME = "$TIMEFRAME"
START_DATE = "$START_DATE"
END_DATE = "$END_DATE"

# Telegram
TELEGRAM_TOKEN = "$TELEGRAM_TOKEN"
TELEGRAM_CHAT_ID = "$TELEGRAM_CHAT_ID"

# Strategy Parameters (from original Pine Script)
SENSITIVITY = 2.4
STUNER = 10
MSTUNER = 8
FILTER_STYLE = "Trending Signals [Mode]"
EOL

      - name: 🧪 Run Backtest (main.py)
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: 📤 Upload Trade Results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: trades-${{ github.run_id }}
          path: results/trades.csv
