# .github/workflows/live.yml
name: 🚀 اجرای لایو سیستم سیگنال

on:
  schedule:
    - cron: '*/15 * * * *'  # هر 15 دقیقه
  workflow_dispatch:        # امکان اجرای دستی

jobs:
  run-live:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install ccxt pandas requests

      - name: Run main.py
        run: python main.py

      - name: Save log
        run: echo "Last run: $(date)" >> logs/live_run.log
