name: Manual Backtest

on:
  workflow_dispatch:
    inputs:
      symbol:
        type: string
        description: 'Trading pair (e.g. BTC-USDT)'
        required: true
        default: 'BTC-USDT'
      timeframe:
        type: string
        description: 'Candle timeframe (e.g. 1h)'
        required: true
        default: '1h'
      start_date:
        type: string
        description: 'Start date (YYYY-MM-DD)'
        required: true
        default: '2023-01-01'
      end_date:
        type: string
        description: 'End date (YYYY-MM-DD)'
        required: true
        default: '2024-01-01'

jobs:
  backtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            pip install pandas ta requests PyYAML
          fi

      - name: Create config directory
        run: mkdir -p config

      - name: Generate backtest config
        env:
          SYMBOL: ${{ github.event.inputs.symbol }}
          TIMEFRAME: ${{ github.event.inputs.timeframe }}
          START_DATE: ${{ github.event.inputs.start_date }}T00:00:00
          END_DATE: ${{ github.event.inputs.end_date }}T00:00:00
        run: |
          echo "backtest:" > config/backtest_config.yml
          echo "  symbol: '$SYMBOL'" >> config/backtest_config.yml
          echo "  timeframe: '$TIMEFRAME'" >> config/backtest_config.yml
          echo "  start_date: '$START_DATE'" >> config/backtest_config.yml
          echo "  end_date: '$END_DATE'" >> config/backtest_config.yml
          echo "  mode: 'manual'" >> config/backtest_config.yml
          echo "risk:" >> config/backtest_config.yml
          echo "  stop_loss_percent: 1.0" >> config/backtest_config.yml
          echo "  take_profit_percent: 3.0" >> config/backtest_config.yml
          echo "debug:" >> config/backtest_config.yml
          echo "  enable_logging: true" >> config/backtest_config.yml
          echo "  log_level: 'INFO'" >> config/backtest_config.yml

      - name: Run main.py
        run: python main.py

      - name: Upload results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: backtest-results
          path: |
            results/
            logs/
            config/backtest_config.yml
