name: Manual Backtest

on:
  workflow_dispatch:
    inputs:
      symbol:
        type: string
        description: 'Trading pair (e.g. BTC-USDT)'
        required: true
        default: 'BTC-USDT'
      timeframe:
        type: string
        description: 'Candle timeframe (e.g. 1h)'
        required: true
        default: '1h'
      start_date:
        type: string
        description: 'Start date (YYYY-MM-DD)'
        required: true
        default: '2023-01-01'
      end_date:
        type: string
        description: 'End date (YYYY-MM-DD)'
        required: true
        default: '2024-01-01'

jobs:
  backtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyYAML pandas ta requests

      - name: Generate backtest config
        env:
          SYMBOL: ${{ github.event.inputs.symbol }}
          TIMEFRAME: ${{ github.event.inputs.timeframe }}
          START_DATE: ${{ github.event.inputs.start_date }}T00:00:00
          END_DATE: ${{ github.event.inputs.end_date }}T00:00:00
        run: |
          mkdir -p config
          cat << EOF > config/backtest_config.yml
backtest:
  symbol: "$SYMBOL"
  timeframe: "$TIMEFRAME"
  start_date: "$START_DATE"
  end_date: "$END_DATE"
  mode: "manual"
EOF

      - name: Run Backtest
        run: python main.py
