name: Manual Backtest

on:
  workflow_dispatch:
    inputs:
      symbol:
        type: string
        description: 'Trading pair'
        default: 'BTC-USDT'
      timeframe:
        type: string
        description: 'Timeframe'
        default: '1h'
      start_date:
        type: string
        description: 'Start date'
        default: '2023-01-01'
      end_date:
        type: string
        description: 'End date'
        default: '2024-01-01'

jobs:
  backtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install
        run: |
          pip install pandas ta requests PyYAML
      - name: Show inputs
        run: |
          echo "Symbol: ${{ github.event.inputs.symbol }}"
          echo "Timeframe: ${{ github.event.inputs.timeframe }}"
          echo "Start: ${{ github.event.inputs.start_date }}"
          mkdir -p config
          echo "backtest:" > config/backtest_config.yml
          echo "  symbol: '${{ github.event.inputs.symbol }}'" >> config/backtest_config.yml
          echo "  timeframe: '${{ github.event.inputs.timeframe }}'" >> config/backtest_config.yml
          echo "  start_date: '${{ github.event.inputs.start_date }}T00:00:00'" >> config/backtest_config.yml
          echo "  end_date: '${{ github.event.inputs.end_date }}T00:00:00'" >> config/backtest_config.yml
      - name: Run
        run: |
          echo "✅ Backtest started. No main.py yet, but workflow works!"
          echo "Config generated in config/backtest_config.yml"
